services:
  php:
    image: "${DRAKY_PHP_IMAGE}"
    environment:
      DRAKY_HOST_UID: "${DRAKY_HOST_UID}"
      DRAKY_HOST_GID: "${DRAKY_HOST_GID}"
      DRAKY_OVERRIDE_HOST_IP: "${DRAKY_HOST_IP}"
      DRAKY_OVERRIDE_HOST_USERNAME: host
      DRAKY_OVERRIDE_HOST_GROUP: host
      DRAKY_OVERRIDE_MAILHOG_HOST: mailhog
      DRAKY_OVERRIDE_WEBSERVER_HOST: webserver
      PHP_IDE_CONFIG: "${DRAKY_PHP_IDE_CONFIG}"
      DRAKY_ENTRYPOINT_DO_CREATE_HOST_USER: "${DRAKY_HOST_UID}"
      DRAKY_PHP_COMPOSER_HASH: "${DRAKY_PHP_COMPOSER_HASH}"
      DRAKY_PHP_COMPOSER_HASH_VERIFY: "${DRAKY_PHP_COMPOSER_HASH_VERIFY}"
      DRAKY_PHP_XDEBUG_VERSION: "${DRAKY_PHP_XDEBUG_VERSION}"
      DRAKY_OVERRIDE_PHP_XDEBUG_PORT: "${DRAKY_PHP_XDEBUG_PORT}"
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "9000" ]
      interval: 1s
      timeout: 10s
      retries: 10
    volumes:
      - "${DRAKY_PROJECT_ROOT}:${DRAKY_PHP_CONTAINER_ROOT}:cached,rw"
      - "./resources:/draky-entrypoint.resources:cached,ro"
      - "./cache/composer:/var/cache/composer:cached,rw"
      - "./init.d:/draky-entrypoint.init.d:cached,ro"
    draky:
      addons:
        - draky-entrypoint