services:
  nginx:
    image: "${DRAKY_NGINX_IMAGE}"
    environment:
      DRAKY_OVERRIDE_NGINX_BACKEND_HOST: "${DRAKY_NGINX_BACKEND_HOST}"
      DRAKY_OVERRIDE_NGINX_SERVER_NAME: "${DRAKY_NGINX_DOMAIN}"
      DRAKY_OVERRIDE_NGINX_SERVER_ROOT: "${DRAKY_NGINX_FRONT_CONTROLLER}"
      DRAKY_ENTRYPOINT_DO_CREATE_HOST_USER: "${DRAKY_HOST_UID}"
    ports:
      - "${DRAKY_NGINX_PORT}:80"
    volumes:
      - "${DRAKY_PROJECT_ROOT}:/var/www/html:cached,ro"
      - "./resources:/draky-entrypoint.resources:cached"
    draky:
      addons:
        - draky-entrypoint