services:
  mariadb:
    image: "${DRAKY_MARIADB_IMAGE}"
    entrypoint: "/draky-entrypoint.sh"
    command: ["docker-entrypoint.sh", "mariadbd"]
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "${DRAKY_MARIADB_DATABASE}"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 1s
      timeout: 10s
      retries: 10
    ports:
      - "${DRAKY_MARIADB_PORT_EXPOSED}:3306"
    volumes:
      - "./resources:/draky-entrypoint.resources:cached,ro"
      - "./initdb.d:/docker-entrypoint-initdb.d:cached,ro"
      - "${DRAKY_PATH_ADDONS}/draky-entrypoint/draky-entrypoint.sh:/draky-entrypoint.sh:cached"
