services:
  mariadb:
    image: "${DRAKY_MARIADB_IMAGE}"
    entrypoint: "/draky-entrypoint.sh"
    command: ["docker-entrypoint.sh", "mariadbd"]
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    volumes:
      - "./resources:/draky-tools.resources:cached,ro"
      - "${DRAKY_PATH_ADDONS}/draky-entrypoint/draky-entrypoint.sh:/draky-entrypoint.sh:cached"
